services:
  products_api:
    build:
      context: .
      dockerfile: Products/Dockerfile
    ports:
      - "5000:5075"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=products_database;Port=5432;Database=productdb;Username=postgres;Password=postgres
      - Redis__ConnectionString=products_cache:6379

    depends_on:
      products_database:
        condition: service_healthy
      products_cache:
        condition: service_started

  products_database:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  products_cache:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


volumes:
  pgdata:
