# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  products:
    image: products
    build:
      context: .
      dockerfile: Products/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5075:5075
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
